JpegBoolean: BooleanCircuit.cpp BooleanCircuit.h BooleanStructure.h BooleanThread.h BooleanTree.cpp BooleanTree.h JpegBooleanMain.cpp
	g++ -O2 BooleanCircuit.cpp BooleanTree.cpp JpegBooleanMain.cpp -lpthread -o JpegBoolean

